<?php
/*------------------------------------------------------------------------

# TZ Portfolio Extension

# ------------------------------------------------------------------------

# Author:    DuongTVTemPlaza

# Copyright: Copyright (C) 2011-2024 TZ Portfolio.com. All Rights Reserved.

# @License - http://www.gnu.org/licenses/gpl-2.0.html GNU/GPL

# Website: http://www.tzportfolio.com

# Technical Support:  Forum - https://www.tzportfolio.com/help/forum.html

# Family website: http://www.templaza.com

# Family Support: Forum - https://www.templaza.com/Forums.html

-------------------------------------------------------------------------*/

namespace TemPlaza\Component\TZ_Portfolio\Site\View\Portfolio;

// No direct access.
use Joomla\CMS\MVC\View\HtmlView as BaseHtmlView;

defined('_JEXEC') or die;

/**
 * Json Portfolio View class for the TZ Portfolio component.
 */
class JsonView extends HtmlView {

    public function display($tpl = null)
    {
//        $this -> items  = $this -> get('Items');
//        $this -> params  = $this -> get('Items');
//        $state          = $this -> get('State');
//        $this -> state  = $state;
//        $this -> params = $state -> get('params');

        parent::display($tpl);


        $html   = $this -> loadTemplate($this -> getLayout());
        var_dump($this -> getLayout());
        var_dump($this -> getLayoutTemplate());
        var_dump($html);

        return json_encode(array('test' => 'fsdfds'));
//        return parent::display($tpl); // TODO: Change the autogenerated stub
    }
}