<?php
/*------------------------------------------------------------------------

# TZ Portfolio Extension

# ------------------------------------------------------------------------

# Author:    DuongTVTemPlaza

# Copyright: Copyright (C) 2011-2024 TZ Portfolio.com. All Rights Reserved.

# @License - http://www.gnu.org/licenses/gpl-2.0.html GNU/GPL

# Website: http://www.tzportfolio.com

# Technical Support:  Forum - https://www.tzportfolio.com/help/forum.html

# Family website: http://www.templaza.com

# Family Support: Forum - https://www.templaza.com/Forums.html

-------------------------------------------------------------------------*/

namespace TemPlaza\Component\TZ_Portfolio\AddOn\Content\Vote\Site\Controller;

use Joomla\CMS\Factory;
use Joomla\CMS\MVC\Controller\BaseController;
use TemPlaza\Component\TZ_Portfolio\Administrator\Library\AddOn\AddOnController;
use TemPlaza\Component\TZ_Portfolio\Administrator\Library\TZ_PortfolioUri;

defined('_JEXEC') or die;

class DisplayController extends AddOnController {
    public function display($cachable = false, $urlparams = array())
    {
        $wa = Factory::getApplication() -> getDocument() -> getWebAssetManager();
//        $wa -> registerStyle('com_tz_portfolio.addon.content.vote',TZ_PortfolioUri::root(true)
//            .'/addons/content/vote/css/vote.css');

        $wa -> registerAndUseScript('com_tz_portfolio.addon.content.vote', TZ_PortfolioUri::root(true) . '/js/modernizr.custom.js',
            array('version' => '2.8.3', 'relative' => true));
        $wa -> registerAndUseScript('com_tz_portfolio.addon.content.vote', TZ_PortfolioUri::root(true) . '/js/classie.min.js',
            array('version' => 'auto', 'relative' => true));
        $wa -> registerAndUseScript('com_tz_portfolio.addon.content.vote', TZ_PortfolioUri::root(true) . '/js/notificationfx.min.js',
            array('version' => 'v=1.0.0', 'relative' => true));

        $wa -> registerAndUseStyle('com_tz_portfolio.addon.content.vote', TZ_PortfolioUri::root(true)
            . '/add-ons/content/vote/css/vote.css', array('version' => 'auto'));
        $wa -> registerAndUseScript('com_tz_portfolio.addon.content.vote', TZ_PortfolioUri::root(true) . '/add-ons/content/vote/js/vote.min.js',
            array('version' => 'auto', 'relative' => true));
        return parent::display($cachable, $urlparams); // TODO: Change the autogenerated stub
    }
}