<?php
/*------------------------------------------------------------------------

# TZ Portfolio Extension

# ------------------------------------------------------------------------

# Author:    DuongTVTemPlaza

# Copyright: Copyright (C) 2011-2024 TZ Portfolio.com. All Rights Reserved.

# @License - http://www.gnu.org/licenses/gpl-2.0.html GNU/GPL

# Website: http://www.tzportfolio.com

# Technical Support:  Forum - https://www.tzportfolio.com/help/forum.html

# Family website: http://www.templaza.com

# Family Support: Forum - https://www.templaza.com/Forums.html

-------------------------------------------------------------------------*/

namespace TemPlaza\Component\TZ_Portfolio\AddOn\Mediatype\Image\Site\View\Portfolio;

// No direct access.
defined('_JEXEC') or die;

use Joomla\CMS\Factory;
use Joomla\CMS\Uri\Uri;
use Joomla\CMS\Filesystem\File;
use Joomla\CMS\MVC\View\HtmlView as BaseHtmlView;
use TemPlaza\Component\TZ_Portfolio\Administrator\Library\TZ_PortfolioUri;

/**
 * Categories view class for the Category package.
 */
class HtmlView extends BaseHtmlView
{
    protected $item                 = null;
    protected $params               = null;
    protected $image                = null;
    protected $head                 = false;
    protected $image_properties     = false;

    public function display($tpl = null)
    {
        $state          = $this -> get('State');
        $params         = $state -> get('params');
        $this -> params = $params;
        $item           = $this -> get('Item');
        $this -> image  = null;

        if($item){
            if($media = $item -> media){
                if(isset($media -> image)){
                    $image          = clone($media -> image);

                    if(isset($image -> url) && $image -> url) {

                        if(!$this -> head) {
                            $this -> head   = true;
                        }

                        $image->temp = $image->url;


                        if ($size = $params->get('mt_cat_image_size', 'o')) {
                            if (isset($image->url) && !empty($image->url)) {
                                $image_url_ext = File::getExt($image->url);
                                if ($params->get('mt_show_original_gif',1) && $image_url_ext == 'gif') {
                                    $size = 'o';
                                }
                                $image_url = str_replace('.' . $image_url_ext, '_' . $size . '.'
                                    . $image_url_ext, $image->url);
                                if ($params->get('mt_image_uikit',0) && file_exists(JPATH_BASE.'/'.$image_url)) {
                                    $this->image_properties =   getimagesize(JPATH_BASE.'/'.$image_url);
                                }
                                $image->url = Uri::base( true ) . '/' . $image_url;
                            }
                        }
                        $this->image = $image;
                    }
                }
            }
            $this -> item   = $item;
        }
        parent::display($tpl); // TODO: Change the autogenerated stub
    }
}
